# Generated by Django 4.2.5 on 2024-01-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_course_description_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='', max_length=200),
        ),
    ]
